// Package templates holds the starter files written by `sql-exporter init`,
// embedded into the binary so init has no runtime file dependencies. The
// embedded config is also the canonical documented example.
package templates

import _ "embed"

// Config is the starter config.yaml written by `init`.
//
//go:embed config.yaml
var Config string

// EnvFormat is the starter .env, with a single %s for the generated hashing key.
const EnvFormat = `# Generated by 'sql-exporter init'. Do not commit this file.
SINGLESTORE_DSN=user:password@tcp(host:3306)/dbname?tls=true
EXPORT_HASH_KEY=%s
`
